### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by KenxinKun** [d6o/portsservice#1]
Hi I'm Borja, I've being asked to review your submission. I will open a few issues here with questions, which is part of the interview process. For starters:

How would you improve your Dockerfile for production? How would you address security?

**Comment by d6o** [comment]
Hi Borja, 

Thanks for taking the time to review my submission.

To improve the Dockerfile for production, I would make the following changes:

**Smaller base image**: I would switch to a smaller, more specific version of the Golang image, such as `golang:1.20-alpine`, Instead of using the `golang:latest` image. This helps to reduce the image size and minimize the attack surface.

**Multi-stage builds**: I would use a multi-stage build to keep the final production image clean and small. This means compiling the application in one stage and copying the compiled binary to another stage with a lightweight base image.

**Non-root user**: I would run the application as a non-root user inside the container to enhance security. This can be done by creating a user and setting the appropriate permissions.

I have created [this PR](https://github.com/d6o/portsservice/pull/5), with the changes above. 

If you'd like me to further optimize the Dockerfile. I can make the image and surface attack even smaller using the empty `scratch` image instead of the `alpine:3.17` for the final production stage. 

Pros:
- Using "scratch" as the base image results in an even smaller image.
- The "scratch" image is empty. Its minimal attack surface makes it more secure than other base images.

Cons:
- The "scratch" image does not have a package manager or any system libraries, making it harder to include additional dependencies, if needed, in the future.
- The "scratch" image doesn't provide any shell or debugging tools, making it more challenging to investigate issues if you need to debug or troubleshoot anything inside the container.

Let me know if you have any questions or need further information.
