### ISSUE TITLE
API specs

### ISSUE THREAD

**Issue by KenxinKun** [d6o/portsservice#2]
Since you used an http server for your API, did you consider other alternatives?
Besides that, how would you write a standard spec for your implementation?

**Comment by d6o** [comment]
Hi Borja,

Yes, I considered other alternatives before choosing to use an HTTP server for my API. I explored options like gRPC, GraphQL, and WebSocket, each with benefits and drawbacks. However, I ultimately decided to use an HTTP server because it's simple to implement, widely supported, and easy for clients to interact with. 

As for writing a standard spec for the implementation, I would use the OpenAPI Specification (or Swagger). This is a widely adopted specification format that enables developers to describe, produce, and consume RESTful APIs. The OpenAPI Specification can be used to generate documentation, client libraries, and server stubs, making it easier to work with the API.

I created [this PR](https://github.com/d6o/portsservice/pull/6), which creates an OpenAPI Specification, compiles it to a static webpage, and creates a new `GET /docs` endpoint which serves the static file.

Let me know if you have any questions or need further information.
